name: Python checks 🐍

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - wireguard_service/**

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Setup UV
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run black
        run: uv run black . --check --diff

      - name: Run isort
        run: uv run isort . --check-only --diff
